site_name: Apache Apex Malhar Documentation
site_favicon: favicon.ico
theme: readthedocs
pages:
- Apache Apex Malhar: index.md
- APIs:
    - SQL: apis/calcite.md
- Operators:
    - Block Reader: operators/block_reader.md
    - CSV Formatter: operators/csvformatter.md
    - CSV Parser: operators/csvParserOperator.md
    - Deduper: operators/deduper.md
    - Enricher: operators/enricher.md
    - File Input: operators/fsInputOperator.md
    - File Output: operators/file_output.md
    - File Splitter: operators/file_splitter.md
    - Filter: operators/filter.md
    - JDBC Poller Input: operators/jdbcPollInputOperator.md
    - JMS Input: operators/jmsInputOperator.md
    - JSON Formatter: operators/jsonFormatter.md
    - JSON Parser: operators/jsonParser.md
    - Kafka Input: operators/kafkaInputOperator.md
    - Transformer: operators/transform.md
    - Windowed Operator: operators/windowedOperator.md
    - XML Parser: operators/xmlParserOperator.md
    - Json Parser: operators/jsonParser.md
    - Json Formatter: operators/jsonFormatter.md
    - Transform Operator: operators/transform.md
    - Csv Formatter: operators/csvformatter.md
    - S3 Output Module: operators/s3outputmodule.md
