site_name: Apache Apex Malhar Documentation
site_favicon: favicon.ico
theme: readthedocs
pages:
- Apache Apex Malhar: index.md
- Development Best Practices: development_best_practices.md
- Operators:
    - Kafka Input: operators/kafkaInputOperator.md
    - File Splitter: operators/file_splitter.md
    - Block Reader: operators/block_reader.md
    - File Output: operators/file_output.md
